In [15]:
import numpy as np
# import import_ipynb

# from lab1 import qr_householder


#based on https://rosettacode.org/wiki/QR_decomposition#Python
def qr_householder(A):
    m, n = A.shape
    maxMn= np.max([m,n])
    minMn = np.min([m,n])

    Q = np.eye(m)
    for i in range(minMn - (m == n)):
        H = np.eye(m)
        householder_matrix = make_householder(A[i:, i])
        H[i:, i:] = householder_matrix
        Q = np.dot(Q, H)
        A = np.dot(H, A)
    return Q, A

def make_householder(a):
    
    # вычисляем u=a−αe1,где α=−sign(a0)∥a∥ 
    norm_a = np.linalg.norm(a)
    v = a / (a[0] + np.copysign(norm_a, a[0]))
    v[0] = 1

    # вычисляем H = I - (2*u*u^t)/||u||^2
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H


def printRounded(arr, round = 3):
    print(np.round(arr, round))

def check_qr_houselolder(m, n):
    A = np.random.rand(m, n)

    Q, R = qr_householder(A)

    q, r = np.linalg.qr(A)

    with np.printoptions(linewidth=9999, precision=3, suppress=True):

        print("**** A")
        print(A)

        print("**** Q from qr_decomposition")
        print(Q)
        print("**** Q from np.linalg.qr")
        print(q)
        print()
    
        print("**** R from qr_decomposition")
        print(R)
        print("**** R from np.linalg.qr")
        print(r)


check_qr_houselolder(7,3)
check_qr_houselolder(2,13)
check_qr_houselolder(20,20)


**** A
[[0.791 0.351 0.669]
 [0.631 0.683 0.394]
 [0.554 0.873 0.804]
 [0.044 0.955 0.901]
 [0.095 0.177 0.43 ]
 [0.403 0.478 0.63 ]
 [0.945 0.008 0.174]]
**** Q from qr_decomposition
[[-0.511  0.1   -0.427  0.126 -0.156 -0.258 -0.663]
 [-0.408 -0.234  0.644 -0.025  0.509  0.109 -0.303]
 [-0.358 -0.419  0.106 -0.578 -0.415 -0.332  0.261]
 [-0.029 -0.724 -0.159  0.643 -0.003 -0.087  0.172]
 [-0.061 -0.093 -0.53  -0.316  0.728 -0.177  0.213]
 [-0.261 -0.182 -0.287 -0.173 -0.12   0.879  0.011]
 [-0.61   0.44   0.049  0.325  0.012 -0.016  0.571]]
**** Q from np.linalg.qr
[[-0.511  0.1   -0.427]
 [-0.408 -0.234  0.644]
 [-0.358 -0.419  0.106]
 [-0.029 -0.724 -0.159]
 [-0.061 -0.093 -0.53 ]
 [-0.261 -0.182 -0.287]
 [-0.61   0.44   0.049]]

**** R from qr_decomposition
[[-1.548 -0.937 -1.112]
 [-0.    -1.283 -1.093]
 [ 0.     0.    -0.491]
 [-0.     0.     0.   ]
 [ 0.     0.    -0.   ]
 [ 0.     0.     0.   ]
 [ 0.    -0.    -0.   ]]
**** R from np.linalg.qr
[[-1.548 -0.937 -1.112]
 [ 0.    